# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-a2a" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "44bd7089f313b0e7cc5370f395f989f74b3f8bc214f17582d54efbb5e0fe72ad"
      url "https://github.com/neprel/git-a2a/releases/download/v#{version}/git-a2a_brew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3621a31034e0980ea7101f423964e30ae5086a787e804f89f86ebb013c9dc1ee"
      url "https://github.com/neprel/git-a2a/releases/download/v#{version}/git-a2a_brew_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "git-a2a"
  desc "Import git modules together with their owning agents"
  homepage "https://github.com/neprel/git-a2a"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-a2a"

  # No zap stanza required

end
