# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-a2a" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "7bc17861a7b51800abb8296049d862abcf5ecab29b948ed38a400989ab54581c"
      url "https://github.com/neprel/git-a2a/releases/download/v#{version}/git-a2a_brew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "95e6ee027efaa4b31a26ade604bf845304919a4359ee1021dbdca9a71a6b4091"
      url "https://github.com/neprel/git-a2a/releases/download/v#{version}/git-a2a_brew_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "git-a2a"
  desc "Import git modules together with their owning agents"
  homepage "https://github.com/neprel/git-a2a"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-a2a"

  # No zap stanza required

end
